[package]
name = "system"
version = "0.1.0"
edition = "2024"

[dependencies]
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.100"
serde = { version = "1.0.219", features = ["derive"] }
wasm-bindgen-futures = "0.4.50"
